name-template: 'Version $NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '👍 Enhancements'
    labels:
      - 'enhancement'   
      - 'documentation'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🔧 Maintenance'
    label: 
       - 'refactor'
       - 'test'
       - 'tests'
exclude-labels:
  - 'skip-changelog'  
  - 'build'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES
