version: 1.0.{build}
clone_folder: c:\utfUnknown
image: Visual Studio 2017
configuration: Release
platform: Any CPU
nuget:
  project_feed: true

deploy: off
build_script:
- ps: dotnet build -c Release 
test_script:
- ps: cd .\tests\
- ps: dotnet test
- ps: cd ..
after_build:
- ps: cd .\src\
- ps: dotnet pack -c Release 
- ps: cd ..
artifacts:
- path: '**\*.nupkg'
- path: '**\test-diag.log'
