version: 1.0.{build}
clone_folder: c:\ude
platform: Any CPU
nuget:
  project_feed: true
matrix:
  fast_finish: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy: off
test_script:
  - nuget.exe install OpenCover -ExcludeVersion
  - OpenCover\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"\"c:\ude\src\Tests\bin\Release\Ude.Tests.dll\" -appveyor -noshadow"  -returntargetcode -filter:"+[Ude]* -[Ude.Tests]* -[Ude.Example]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml"
 
